version: '3.8'

services:
  postgres:
    container_name: trabalho2_devWeb_postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=locadora